
DEVELOPMENT:
#  SOCIAL_TWITTER:
#    consumer_key: 'EVjDQnCBVFnMYcSQoMr2xg'
#    consumer_secret: '62VFxTHg55XqU2A5AFfnEuFQdNWFAoPFSCpUirFyO0'
    
  SOCIAL_FACEBOOK:
    consumer_key: '330570673686097'
    consumer_secret: '1f948a99fc6141a4dd5f48edc4537e94'
    request_token_params:
      scope: 'email,publish_stream,manage_pages, user_events,user_groups, create_event, user_photos'

PRODUCTION:
  SECRET_KEY: "a8a46a7375654fd9b2c22ced8c0c6f10"
  GOOGLE_ANALYTICS_ID: "UA-3425506-3"
  #SOCIAL_APP_URL : "http://www.itchyknows.com"

  
#  SOCIAL_TWITTER:
#    consumer_key: 'EVjDQnCBVFnMYcSQoMr2xg'
#    consumer_secret: '62VFxTHg55XqU2A5AFfnEuFQdNWFAoPFSCpUirFyO0'

    
  SOCIAL_FACEBOOK:
    consumer_key: '105001999640752'
    consumer_secret: '551630c46caa96d19b037bf1257afd5e'
    request_token_params:
      scope: 'email,publish_stream,manage_pages, user_events,user_groups, create_event, user_photos'